//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 2024-03-11
//  @ Author : 
//
//




public class Account {
	private String accNum;
	private String customerName;
	private long balance;
	private double interest;
	public void Account() {
	
	}
	
	public void Account(String accNum, String customerName, long balance, double interest) {
	
	}
	
	public void withdraw(long money) {
	
	}
	
	public void deposit(long money) {
	
	}
	
	public double getCalInterest() {
	
	}
}
